// loading database model
import { Clients, Passes } from '../models/index.js';

// loading service functions
import { transformData } from '../public/javascripts/functions.js';

// returning clients list
export const getClients = async function(req, res) {
    try {
        let clients = await Clients.findAll({
            order: [['surname', 'ASC'], ['name', 'ASC']],
        });
        clients = transformData(clients);
        res.render('clients', {
            title: 'Список клиентов',
            clients
        });
    } catch(err) {
        console.log(err);
        res.redirect('/');
    }
};

// returning blank client card
export const newClient = function(req, res) {
    let button1 = {
        action : "/clients/create",
        name : "Создать",
    };
    let button2 = {
        action : "/clients",
        name : "Отмена",
    };
    res.render("clientcard", {
        button1,
        button2,
        title: "Новый клиент",
    });
};

//отправка данных с формы создания клиента в БД
export const createClient = async function (req, res) {
    if(!req.body) return res.sendStatus(400);
    const name = req.body.name;
    const surname = req.body.surname;
    const cellphone = req.body.cellphone;
    const vk = req.body.vk;
    const insta = req.body.insta;
    const info = req.body.info;
    const birthday = req.body.birthday ? req.body.birthday : null;
    try {
        let client = await Clients.create({Name: name, Surname: surname, Cellphone: cellphone, VK: vk, Insta: insta, Info: info, Birthday: birthday});
        client = client.dataValues;
        console.log('Client autogenerated id:', client.idClients, client.Name, client.Surname);
        res.redirect(`/clients/${client.idClients}`);
    } catch(err) {
        console.log(err);
        return res.redirect('back');
    };
};

// поиск клиента по фамилии
export const clientsFilter = async function (req, res) {
    const surname = req.body.filterSurname;
    try {
        let client = await Clients.findAll({
            where: {
                Surname: surname
            }
        });
        let clients = transformData(client);
        res.render('clients', {
            clients
        });
    } catch(err) {
        console.log(err);
        res.redirect('/clients');
    };
};

//возврат карточки клиента по ID
export const getClientCard = async function (req, res) {
    const id = req.params.idClients;
    try {
        let client = await Clients.findAll({
            where: {
                idClients: id
            }
        });
        let passes = await Passes.findAll({
            where: {
                ID_Clients: id
            }
        });
        client = transformData(client);
        passes = transformData(passes);
        let button1 = {
            action: "/clients/update",
            name: "Редактировать",
        };
        let button2 = {
            action: "/clients/delete",
            name: "Удалить",
        };
        res.render('clientcard', {
            button1,
            button2,
            title: "Карточка клиента",
            showpasses: true,
            client: client[0],
            passes,
        });
    } catch (err) {
        console.log(err);
    };
};

//редактирование карточки клиента
export const updateClient = async function (req, res) {
    if (req.body) return res.sendStatus(400);
    const id = req.body.id;
    const name = req.body.name;
    const surname = req.body.surname;
    const cellphone = req.body.cellphone;
    const vk = req.body.vk;
    const insta = req.body.insta;
    const info = req.body.info;
    const birthday = req.body.birthday ? req.body.birthday : null;
    try {
        let client = await Clients.update({
            Name: name,
            Surname: surname,
            Cellphone: cellphone,
            VK: vk,
            Insta: insta,
            Info: info,
            Birthday: birthday,
        },  {
                where: {
                    idClients: id
                }, returning: true
            });
        console.log(client);
        console.log(`Update client ${surname} ${name} sucsessful`);
        res.redirect(`/clients/${id}`);
    } catch (err) {
        console.log(err);
        res.redirect('back');
    }
};

//удаление клиента из БД
export const deleteClient = async function(req, res) {
    if(!req.body) return res.sendStatus(400);
    const id = req.body.id;
    try {
        await Clients.destroy({
            where: {
                idClients: id
            }
        });
    } catch (err) {
        console.log(err);
    }
    res.redirect("/clients");
};