// loading database model
const model = require('../boot/db.js')

// loading service functions
const {transformData, transformDate} = require("../public/javascripts/functions.js");

exports.getExpences = async function (req, res) {
    try {
        let expences = await model.expence.findAll();
        let types = await model.expencestype.findAll();
        expences = transformData(expences);
        types = transformData(types);
        expences = expences.map(item => {
            let idType = item.ID_ExpencesTypes;
            item.Type = types.find(item => item.idExpencesTypes === idType).Type;
            item.Date = transformDate(item.Date);
            return item
        });
        console.log(expences, types);
        res.render('expences', {
            title: 'Список расходов',
            expences,
            types,
        });
    } catch (err) {
        console.log(err);
        res.redirect('/');
    }
};

exports.getExpencesTypes = async function (req, res) {
    try {
        let expencestypes = await model.expencestype.findAll();
        types = transformData(expencestypes);
        console.log(types);
        res.render('expencestypes', {
            title: 'Типы расходов',
            types,
        });
    } catch (err) {
        console.log(err);
        res.redirect('/expences');
    }
};

exports.createExpencesType = async function (req, res) {
    let type = req.query.type;
    try {
        let row = await model.expencestype.create({Type: type});
        console.log('Expence type autogenerated id = ' + row);
        res.redirect('/expences/types');
    } catch (err) {
        console.log(err);
        res.redirect('/expences/types');
    }
};

exports.createExpence = async function (req, res) {
    let type = req.query.type;
    let date = req.query.date;
    let cost = req.query.cost;
    let info = req.query.info;
    try {
        let row = await model.expence.create({ID_ExpencesTypes: type, Date: date, Cost: cost, Info: info});
        console.log(row);
        console.log('Expence autogenerated id = ' + row.idExpences);
        res.redirect('/expences');
    } catch(err) {
        console.log(err);
        res.redirect('/expences');
    }
};

exports.deleteExpence = async function (req, res) {
    if(!req.body) return res.sendStatus(400);
    const id = req.body.id;
    try {
        await model.expence.destroy({
            where: {
                idExpences: id
            }
        });
    } catch (err) {
        console.log(err);
        res.redirect('/expences');
    }
};



