// loading database model
const model = require('../boot/db.js')

// loading service functions
const {transformData, transformDate} = require("../public/javascripts/functions.js");

exports.getExpenses = async function (req, res) {
    try {
        let expenses = await model.expense.findAll();
        let expensesTypes = await model.expensesType.findAll({
            order: [['Type', 'ASC']]
        });
        expenses = transformData(expenses);
        expensesTypes = transformData(expensesTypes);
        expenses = expenses.map(item => {
            let idType = item.ID_ExpensesTypes;
            item.Type = expensesTypes.find(item => item.idExpensesTypes === idType).Type;
            return item
        });
        console.log(`Found ${expenses.length} expenses`);
        res.render('expenses', {
            title: 'Список расходов',
            expenses,
            expensesTypes
        });
    } catch (err) {
        console.log(err);
        res.redirect('/');
    }
};

exports.createExpense = async function (req, res) {
    let type = req.body.type;
    let date = req.body.date;
    let cost = req.body.cost;
    let info = req.body.info;
    try {
        let row = await model.expense.create({ID_ExpensesTypes: type, Date: date, Cost: cost, Info: info});
        console.log(row);
        console.log('Expense autogenerated id = ' + row.idExpenses);
        res.redirect('/expenses');
    } catch(err) {
        console.log(err);
        res.redirect('/expenses');
    }
};

exports.updateExpense = async function (req, res) {
    const {id, type, date, cost, info} = req.body
    console.log(req.body)
    try {
        await model.expense.update({Type: type, Date: date, Cost: cost, Info: info}, {
            where: {
                idExpenses: id
            }
        })
        console.log(`Updated expenseType with id = ${id}`)
        res.end()
    } catch (err) {
        console.log(err)
        res.end()
    }
}

exports.deleteExpense = async function (req, res) {
    const id = req.params.idExpenses;
    try {
        await model.expense.destroy({
            where: {
                idExpenses: id
            }
        });
        console.log(`Deleted expenseType with id = ${id}`)
        res.end()
    } catch (err) {
        console.log(err);
        res.end();
    }
};



