// loading database model
const model = require('../boot/db.js')

// loading service functions
const {transformData} = require("../public/javascripts/functions.js");

//Get all expense types
exports.getExpenseTypes = async function (req, res) {
    try {
        let expensesTypes = await model.expensesType.findAll({
            order: [['Type', 'ASC']]
        })
        expensesTypes = transformData(expensesTypes)
        console.log(`Found ${expensesTypes.length} expensesTypes`)
        res.render('expensesTypes', {
            title: 'Типы расходов',
            expensesTypes
        })
    } catch (err) {
        console.log(err)
        res.redirect('back')
    }
}

//Creating new expense type
exports.createExpenseType = async function (req, res) {
    const type = req.body.type;
    const info = req.body.info;
    try {
        let expensesType = await model.expensesType.create({Type: type, Info: info})
        console.log('ExpenseType autogenerated id:', expensesType.dataValues.idExpensesTypes);
        res.redirect('back');
    } catch (err) {
        console.log(err)
        res.redirect('back')
    }
}

//Update expense type
exports.updateExpenseType = async function (req, res) {
    const id = req.body.id;
    const type = req.body.type;
    const info = req.body.info;
    try {
        await model.expensesType.update({Type: type, Info: info}, {
            where: {
                idExpensesTypes: id
            }
        })
        console.log(`Updated expenseType with id = ${id}`)
    } catch (err) {
        console.log(err)
    }
};

//Delete expense type
exports.deleteExpenseType = async function (req, res) {
    const id = req.params.idExpensesType;
    try {
        await model.expensesType.destroy({
            where: {
                idExpensesTypes: id
            }
        })
        console.log(`Deleted expenseType with id = ${id}`)
    } catch (err) {
        console.log(err)
    }
};