// loading database model
import { ExpensesTypes } from "../models/index.js";

// loading service functions
import { transformData } from '../public/javascripts/functions.js';

//Get all expense types
export const getExpenseTypes = async function (req, res) {
    try {
        let expensesTypes = await ExpensesTypes.findAll({
            order: [['Type', 'ASC']]
        })
        expensesTypes = transformData(expensesTypes)
        console.log(`Found ${expensesTypes.length} expensesTypes`)
        res.render('expensesTypes', {
            title: 'Типы расходов',
            expensesTypes
        })
    } catch (err) {
        console.log(err)
        res.redirect('back')
    }
}

//Creating new expense type
export const createExpenseType = async function (req, res) {
    const type = req.body.type;
    const info = req.body.info;
    try {
        let expensesType = await ExpensesTypes.create({Type: type, Info: info})
        console.log('ExpenseType autogenerated id:', expensesType.dataValues.idExpensesTypes);
        res.redirect('back');
    } catch (err) {
        console.log(err)
        res.redirect('back')
    }
}

//Update expense type
export const updateExpenseType = async function (req, res) {
    const id = req.body.id;
    const type = req.body.type;
    const info = req.body.info;
    try {
        await ExpensesTypes.update({Type: type, Info: info}, {
            where: {
                idExpensesTypes: id
            }
        })
        console.log(`Updated expenseType with id = ${id}`)
    } catch (err) {
        console.log(err)
    }
};

//Delete expense type
export const deleteExpenseType = async function (req, res) {
    const id = req.params.idExpensesType;
    try {
        await ExpensesTypes.destroy({
            where: {
                idExpensesTypes: id
            }
        })
        console.log(`Deleted expenseType with id = ${id}`)
    } catch (err) {
        console.log(err)
    }
};