// loading database model
import { Expenses, ExpensesTypes } from '../models/index.js'

// loading service functions
import { transformData } from '../public/javascripts/functions.js';

export const getExpenses = async function (req, res) {
    try {
        let expenses = await Expenses.findAll();
        let expensesTypes = await ExpensesTypes.findAll({
            order: [['Type', 'ASC']]
        });
        expenses = transformData(expenses);
        expensesTypes = transformData(expensesTypes);
        expenses = expenses.map(item => {
            let idType = item.ID_ExpensesTypes;
            item.Type = expensesTypes.find(item => item.idExpensesTypes === idType).Type;
            return item
        });
        console.log(`Found ${expenses.length} expenses`);
        res.render('expenses', {
            title: 'Список расходов',
            expenses,
            expensesTypes
        });
    } catch (err) {
        console.log(err);
        res.redirect('/');
    }
};

export const createExpense = async function (req, res) {
    let type = req.body.type;
    let date = req.body.date;
    let cost = req.body.cost;
    let info = req.body.info;
    try {
        let row = await Expenses.create({ID_ExpensesTypes: type, Date: date, Cost: cost, Info: info});
        console.log(row);
        console.log('Expense autogenerated id = ' + row.idExpenses);
        res.redirect('/expenses');
    } catch(err) {
        console.log(err);
        res.redirect('/expenses');
    }
};

export const updateExpense = async function (req, res) {
    const {id, type, date, cost, info} = req.body
    console.log(req.body)
    try {
        await Expenses.update({Type: type, Date: date, Cost: cost, Info: info}, {
            where: {
                idExpenses: id
            }
        })
        console.log(`Updated expenseType with id = ${id}`)
        res.end()
    } catch (err) {
        console.log(err)
        res.end()
    }
}

export const deleteExpense = async function (req, res) {
    const id = req.params.idExpenses;
    try {
        await Expenses.destroy({
            where: {
                idExpenses: id
            }
        });
        console.log(`Deleted expenseType with id = ${id}`)
        res.end()
    } catch (err) {
        console.log(err);
        res.end();
    }
};



