// loading database model
const model = require('../boot/db.js')

// loading service functions
const {transformData, transformDate} = require("../public/javascripts/functions.js");

//Get all income types
exports.getIncomeTypes = async function (req, res) {
    try {
        let incometypes = await model.incometype.findAll({
            order: [['Type', 'ASC']]
        })
        incometypes = transformData(incometypes)
        console.log(`Found ${incometypes.length} incometypes`)
        res.render('incometypes', {
            title: 'Типы доходов',
            incometypes
        })
    } catch (err) {
        console.log(err)
        res.redirect('back')
    }
}

//Creating new incometype
exports.createIncomeType = async function (req, res) {
    const type = req.body.type;
    const info = req.body.info;
    try {
        let incometype = await model.incometype.create({Type: type, Info: info})
        console.log('Incometype autogenerated id:', incometype.dataValues.idIncomeTypes);
        res.redirect('back');
    } catch (err) {
        console.log(err)
        res.redirect('back')
    }
}

//Update incometype
exports.updateIncomeType = async function (req, res) {
    const id = req.body.id;
    const type = req.body.type;
    const info = req.body.info;
    try {
        await model.incometype.update({Type: type, Info: info}, {
            where: {
                idIncomeTypes: id
            }
        })
        console.log(`Updated incometype with id = ${id}`)
    } catch (err) {
        console.log(err)
    }
};

//Delete incometype
exports.deleteIncomeType = async function (req, res) {
    const id = req.params.idIncomeTypes;
    try {
        await model.passtype.destroy({
            where: {
                idIncomeTypes: id
            }
        })
        console.log(`Deleted incometype with id = ${id}`)
    } catch (err) {
        console.log(err)
    }
};