// loading database model
const model = require('../boot/db.js')

// loading service functions
const {transformData} = require("../public/javascripts/functions.js");

//getting all passtypes
exports.getPasstypes = async function (req, res) {
    try {
        let passtypes = await model.passtype.findAll({
            order: [['Amount', 'ASC']]
        })
        passtypes = transformData(passtypes)
        console.log(`Found ${passtypes.length} passtypes`)
        res.render('passtypes', {
            passtypes,
            title: 'Типы абонементов',
        });
    } catch (err) {
        console.log(err)
        res.redirect('back')
    }
};

//Creating new PassType
exports.createPasstype = async function (req, res) {
    const type = req.body.type;
    const amount = req.body.amount;
    const week = req.body.week;
    const cost = req.body.cost;
    try {
        let passtype = await model.passtype.create({Type: type, Amount: amount, Week: week, Cost: cost})
        console.log('Passtype autogenerated id:', passtype.dataValues.idPassTypes);
        res.redirect('/passtypes');
    } catch (err) {
        console.log(err)
        res.redirect('/passtypes')
    }
};

//Update passtype
exports.updatePasstype = async function (req, res) {
    const id = req.body.id;
    const type = req.body.type;
    const amount = req.body.amount;
    const week = req.body.week;
    const cost = req.body.cost;
    try {
        await model.passtype.update({Type: type, Amount: amount, Week: week, Cost: cost}, {
            where: {
                idPassTypes: id
            }
        })
        console.log(`Updated passtype with id = ${id}`)
    } catch (err) {
        console.log(err)
    }
};

//Delete passtype
exports.deletePasstype = async function (req, res) {
    const id = req.params.idPassType;
    try {
        await model.passtype.destroy({
            where: {
                idPassTypes: id
            }
        })
        console.log(`Deleted passtype with id = ${id}`)
    } catch (err) {
        console.log(err)
    }
};