// loading database model
import { PassTypes } from "../models/index.js";

// loading service functions
import { transformData } from "../public/javascripts/functions.js";

//getting all pass types
export const getPassTypes = async function (req, res) {
    try {
        let passTypes = await PassTypes.findAll({
            order: [['Amount', 'ASC']]
        })
        passTypes = transformData(passTypes)
        console.log(`Found ${passTypes.length} passtypes`)
        res.render('passtypes', {
            passTypes,
            title: 'Типы абонементов',
        });
    } catch (err) {
        console.log(err)
        res.redirect('back')
    }
};

//Creating new PassType
export const createPasstype = async function (req, res) {
    const type = req.body.type;
    const amount = req.body.amount;
    const week = req.body.week;
    const cost = req.body.cost;
    try {
        let passtype = await PassTypes.create({Type: type, Amount: amount, Week: week, Cost: cost})
        console.log('Passtype autogenerated id:', passtype.dataValues.idPassTypes);
        res.redirect('/passtypes');
    } catch (err) {
        console.log(err)
        res.redirect('/passtypes')
    }
};

//Update passtype
export const updatePasstype = async function (req, res) {
    const id = req.body.id;
    const type = req.body.type;
    const amount = req.body.amount;
    const week = req.body.week;
    const cost = req.body.cost;
    try {
        await PassTypes.update({Type: type, Amount: amount, Week: week, Cost: cost}, {
            where: {
                idPassTypes: id
            }
        })
        console.log(`Updated passtype with id = ${id}`)
    } catch (err) {
        console.log(err)
    }
};

//Delete passtype
export const deletePasstype = async function (req, res) {
    const id = req.params.idPassType;
    try {
        await PassTypes.destroy({
            where: {
                idPassTypes: id
            }
        })
        console.log(`Deleted passtype with id = ${id}`)
    } catch (err) {
        console.log(err)
    }
};