// loading database model
const model = require('../boot/db.js')

// loading service functions
const {transformData, transformDate} = require("../public/javascripts/functions.js");

//getting all passes
exports.getPasses = async function (req, res) {
    try {
        let passes = await model.pass.findAll()
        let clients = await model.client.findAll({
            attributes: ['idClients', 'Name', 'Surname']
        })
        let passtypes = await model.passtype.findAll({
            attributes: ['idPassTypes', 'Type']
        })
        passes = transformData(passes)
        clients = transformData(clients)
        passtypes = transformData(passtypes)
        passes = passes.map(item => {
            let idClient = item.ID_Clients;
            let idPassType = item.ID_PassTypes
            let client = clients.find(item => item.idClients === idClient);
            item.Name = client.Name;
            item.Surname = client.Surname;
            item.Passtype = passtypes.find(item => item.idPassTypes === idPassType).Type;
            item.DateStart = transformDate(item.DateStart);
            item.DateEnd = transformDate(item.DateEnd);
            return item;
        });
        console.log(`Found ${passes.length} passes`)
        res.render('passes.hbs', {
            passes,
            title: 'Список абонементов',
        });
    } catch (err) {
        console.log(err)
        res.redirect('back')
    }
}

//create new pass form
exports.newPass = async function (req, res) {
    let client;
    if (req.body.id) {
        client = {
            id: req.body.id,
            name: req.body.name,
            surname: req.body.surname,
        }
    }
    try {
        let clients = await model.client.findAll({
            attributes: ['idClients', 'Name', 'Surname'],
            order:[['Surname', 'ASC']]
        })
        let passtypes = await model.passtype.findAll({
            attributes:['idPassTypes', 'Type']
        })
        clients = transformData(clients);
        passtypes=transformData(passtypes);
        console.log(`Found ${clients.length} clients and ${passtypes.length} passtypes`);
        let button1 = {
            action: "/passes/create",
            name: "Создать",
        };
        let button2 = {
            action: "javascript:history.go(-1)",
            name: "Отмена",
        }
        res.render("pass", {
            title: 'Создание нового абонемента',
            button1,
            button2,
            passtypes,
            clients,
            client,
        });
    } catch (err) {
        console.log(err)
        res.redirect('back')
    }
}

//posting new pass to database
exports.createPass = async function (req, res) {
    let idClient = req.body.idClient;
    let idPassType = req.body.idPassType;
    let startDate = new Date(req.body.startDate);
    try {
        let passtypes = await model.passtype.findAll({
            attributes:['Amount', 'Week', 'Cost'],
            where: {
                idPassTypes: idPassType
            }
        })
        passtypes = transformData(passtypes)
        let endDate = new Date();
        endDate.setDate(startDate.getDate() + 7 * passtypes.Week - 1);
        let pass = await model.pass.create({ID_Client: idClient, ID_PassTypes: idPassType, DateStart: startDate, DateEnd: endDate, ClassesLeft: passtypes.Amount, Cost: passtypes.Cost})
        pass = pass.dataValues
        console.log(`Pass autogenerated ID: ${pass.idPasses}`)
        res.redirect(`/passes/${pass.idPasses}`)
    } catch (err) {
        console.log(err)
        res.redirect('/passes/newpass')
    }
};

//вывод абонемента по его id
exports.getPass = function (request, response) {
    const id = request.params.idPasses;
    pool.query('SELECT * FROM passes WHERE idPasses = (?)', [id], function (err, result) {
        if (err) {
            console.log(err);
        }
        result = JSON.parse(JSON.stringify(result[0]));
        console.log(result);
        const query1 = query('SELECT Name, Surname FROM clients WHERE idClients = (?)', [result.ID_Client]);
        const query2 = query('SELECT Type FROM passtypes WHERE idPassType = (?)', [result.ID_PassTypes]);
        Promise.all([query1, query2]).then(function (result) {
            let pass = Array.from(JSON.parse(JSON.stringify(result)));
            console.log(pass);
        });
    });
    response.send('Not available');
};

//редактирование абонемента

exports.editPass = function (request, response) {

};

//удаление абонемента

exports.deletePass = function (request, response) {

};