// loading database model
const model = require('../boot/db.js')

// loading service functions
const {transformData, transformDate} = require("../public/javascripts/functions.js");

//getting all passes
exports.getPasses = async function (req, res) {
    try {
        let passes = await model.pass.findAll()
        let clients = await model.client.findAll({
            attributes: ['idClients', 'Name', 'Surname']
        })
        let passtypes = await model.passtype.findAll({
            attributes: ['idPassTypes', 'Type']
        })
        passes = transformData(passes)
        clients = transformData(clients)
        passtypes = transformData(passtypes)
        passes = passes.map(item => {
            let idClient = item.ID_Clients;
            let idPassType = item.ID_PassTypes
            let client = clients.find(item => item.idClients === idClient);
            item.Name = client.Name;
            item.Surname = client.Surname;
            item.Passtype = passtypes.find(item => item.idPassTypes === idPassType).Type;
            item.DateStart = transformDate(item.DateStart);
            item.DateEnd = transformDate(item.DateEnd);
            return item;
        });
        console.log(`Found ${passes.length} passes`)
        res.render('passes.hbs', {
            passes,
            title: 'Список абонементов',
        });
    } catch (err) {
        console.log(err)
        res.redirect('back')
    }
}

//create new pass form
exports.newPass = async function (req, res) {
    let client;
    if (req.body.id) {
        client = {
            id: req.body.id,
            name: req.body.name,
            surname: req.body.surname,
        }
    }
    try {
        let clients = await model.client.findAll({
            attributes: ['idClients', 'Name', 'Surname'],
            order:[['Surname', 'ASC']]
        })
        let passtypes = await model.passtype.findAll({
            attributes:['idPassTypes', 'Type']
        })
        clients = transformData(clients);
        passtypes=transformData(passtypes);
        console.log(`Found ${clients.length} clients and ${passtypes.length} passtypes`);
        let button1 = {
            action: "/passes/create",
            name: "Создать",
        };
        let button2 = {
            action: "javascript:history.go(-1)",
            name: "Отмена",
        }
        res.render("newpass", {
            title: 'Создание нового абонемента',
            button1,
            button2,
            passtypes,
            clients,
            client,
        });
    } catch (err) {
        console.log(err)
        res.redirect('back')
    }
}

//posting new pass to database
exports.createPass = async function (req, res) {
    let idClient = req.body.idClient;
    let idPassType = req.body.idPassType;
    let startDate = new Date(req.body.startDate);
    try {
        let passtypes = await model.passtype.findAll({
            attributes:['Amount', 'Week', 'Cost'],
            where: {
                idPassTypes: idPassType
            }
        })
        passtypes = passtypes[0].dataValues
        let endDate = new Date();
        endDate.setDate(startDate.getDate() + 7 * passtypes.Week - 1);
        let pass = await model.pass.create({ID_Clients: idClient, ID_PassTypes: idPassType, DateStart: startDate, DateEnd: endDate, ClassesLeft: passtypes.Amount, Cost: passtypes.Cost})
        pass = pass.dataValues
        console.log(`Pass autogenerated ID: ${pass.idPasses}`)
        res.redirect(`/passes/${pass.idPasses}`)
    } catch (err) {
        console.log(err)
        res.redirect('/passes/newpass')
    }
};

//вывод абонемента по его id
exports.getPass = async function (req, res) {
    const id = req.params.idPasses;
    try {
        let pass = await model.pass.findAll({
            where: {
                idPasses: id
            }
        })
        pass = pass[0].dataValues
        let client = await model.client.findAll({
            attributes: ['Name', 'Surname'],
            where: {
                idClients: pass.ID_Clients
            }
        })
        client = client[0].dataValues
        let passtype = await model.passtype.findAll({
            attributes: ['Type'],
            where: {
                idPassTypes: pass.ID_PassTypes
            }
        })
        passtype = passtype[0].dataValues
        pass.Name = client.Name
        pass.Surname = client.Surname
        pass.Type = passtype.Type
        res.render('passcard', {
            title: `Абонемент №${pass.idPasses}`,
            pass,
        })
    } catch (err) {
        console.log(err)
        res.redirect('/passes')
    }
};

//редактирование абонемента

exports.editPass = function (request, response) {

};

//удаление абонемента

exports.deletePass = async function (req, res) {
    let id = req.params.idPasses
    try {
        await model.pass.destroy({
            where: {
                idPasses: id
            }
        })
        console.log(`Deleted pass with id = ${id}`)
        res.redirect('back')
    } catch (err) {
        console.log(err)
        res.redirect('back')
    }
};